-- INSERT GAMES
PRAGMA foreign_keys = ON;

-- Note: Data names and descriptions were randomly generated by using a LLM Model for our convenience. I just wanted to let you know about it for ensuring 100% honesty and clarity.
INSERT INTO GameDefinitions
            (name, description, difficulty)
    VALUES  ('PacMan', 'Eat as many pills as you can. Stun ghosts after popping a power pill.', 3);

INSERT INTO GameDefinitions
            (name, description, difficulty)
    VALUES  ('Mappy', 'Catch the evil burglar-cats and return stolen equipment. Only one catch— you are a mouse.', 4);

INSERT INTO GameDefinitions
            (name, description, difficulty)
    VALUES  ('Missile Command', 'Destroy incoming missiles!', 2);

INSERT INTO GameDefinitions
            (name, description, difficulty)
    VALUES  ('Breakout!', 'Break through the wall to save yourself and your fellow astronauts!', 4);

INSERT INTO GameDefinitions
            (name, description, difficulty)
    VALUES  ('Battlezone', 'Control a tank through 3-dimensional vector graphics, destroy enemy tanks, and find the enemy factories near the volcano!', 8);


-- For our custom games:

INSERT INTO GameDefinitions
            (name, description, difficulty)
    VALUES  ('Tank Game (Efe)', 'Control a tank through the 2-dimensional canvas, 
        destroy as many targets as you can in a limited amount of time while avoiding collision', 6);

INSERT INTO GameDefinitions
            (name, description, difficulty)
    VALUES  ('Adventure Game', 'A text-based adventure game where you collect gold!', 8);


-- INSERT PLAYERS
INSERT INTO Players
            (username, email)
    VALUES  ('Peter', 'peter@gmail.com');

INSERT INTO Players
            (username, email)
    VALUES  ('Paul', 'paul@gmail.com');

INSERT INTO Players
            (username, email)
    VALUES  ('Mary', 'mary@gmail.com');

INSERT INTO Players
            (username, email)
    VALUES  ('Efe', 'efe@gmail.com');
    
INSERT INTO Players
            (username, email)
    VALUES  ('Joe', 'joe@gmail.com');

-- INSERT GAMES PLAYED
INSERT INTO GamePlays
            (game_definition_id, player_id, score, outcome)
    VALUES  (1, 1, 1040, 'Passed Cherry Level');

INSERT INTO GamePlays
            (game_definition_id, player_id, score, outcome)
    VALUES  (1, 1, 3650, 'Passed Mango Level');

INSERT INTO GamePlays
            (game_definition_id, player_id, score, outcome)
    VALUES  (2, 2, 31650, 'Made it to second bonus round');

INSERT INTO GamePlays
            (game_definition_id, player_id, score, outcome)
    VALUES  (6, 4, 30, 'Tank was collided or time was up');
    
INSERT INTO GamePlays
            (game_definition_id, player_id, score, outcome)
    VALUES  (6, 4, 50, 'Tank was collided or time was up');
      
INSERT INTO GamePlays
            (game_definition_id, player_id, score, outcome)
    VALUES  (7, 3, 31650, 'Made it to second bonus round');